#
# Copyright (C) 2026 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: main-build

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - 'main'

jobs:
  builder-image:
    name: Build and publish builder OCI image
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: build builder image
        id: builder-image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: podman-desktop-kind-ext-builder
          tags: next ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          containerfiles: |
            build/Containerfile.builder
          context: .
          oci: true

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish builder to ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          image: ${{ steps.builder-image.outputs.image }}
          tags: ${{ steps.builder-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
  
  extension-image:
    name: Build and publish extension OCI image ${{ matrix.airgap == 'true' && '(Air Gap)' || ''  }}
    runs-on: ubuntu-24.04
    needs: builder-image
    strategy:
      matrix:
        airgap: ['true', 'false']

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Kind binary for airgapped image
        if: ${{ matrix.airgap == 'true' }}
        run: |
          mkdir bin
          curl -Lo ./bin/kind-linux-amd64 https://kind.sigs.k8s.io/dl/v0.31.0/kind-linux-amd64
          chmod +x ./bin/kind-linux-amd64
          curl -Lo ./bin/kind-linux-arm64 https://kind.sigs.k8s.io/dl/v0.31.0/kind-linux-arm64
          chmod +x ./bin/kind-linux-arm64

          curl -Lo ./bin/kind-darwin-amd64 https://kind.sigs.k8s.io/dl/v0.31.0/kind-darwin-amd64
          chmod +x ./bin/kind-darwin-amd64
          curl -Lo ./bin/kind-darwin-arm64 https://kind.sigs.k8s.io/dl/v0.31.0/kind-darwin-arm64
          chmod +x ./bin/kind-darwin-arm64

          curl -Lo ./bin/kind-windows-amd64.exe https://kind.sigs.k8s.io/dl/v0.31.0/kind-windows-amd64
          chmod +x ./bin/kind-windows-amd64.exe

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: build extension image
        id: extension-image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: podman-desktop-kind-ext${{ matrix.airgap == 'true' && '-airgap' || ''  }}
          tags: next ${{ github.sha }}
          archs: amd64, arm64
          containerfiles: |
            build/Containerfile
          context: .
          oci: true
          build-args: AIRGAP=${{ matrix.airgap }}

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: publish extension to ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          image: ${{ steps.extension-image.outputs.image }}
          tags: ${{ steps.extension-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
